### ISSUE TITLE
GUI (Streamlit)

### ISSUE THREAD

**Issue by PlatonB** [PlatonB/high-perf-bio#24]
Задачи:
- [x] Создать классы, в инитах которых будет накапливаться инпут, полностью совместимый с уже привычным из `argparse`.
    - [x] Знакомые по CLI приветственные принты реализовать в виде раскрывающихся блоков (`st.expander`).
    - [x] Все виджеты кроме выбора компонента _high-perf-bio_ завернуть в формы (`st.form`) с кнопкой запуска (`st.form_submit_button`). Если тупо, без формы, накидать виджетов, то этап сбора настроек будет проскакиваться.
- [x] Создать модуль (рабочее название - _GUI.py_):
    - [x] Импорт GUI-классов, описанных чуть выше.
    - [x] Импорт основных классов всех компонентов с подачей в иниты объектов, мимикрирующих под творения _argparse_.
    - [x] Выпадающий список с тулзами.
    - [x] Проверка, нажал ли исследователь кнопку запуска.
    - [x] Спиннер (`st.spinner`), крутящийся, пока задача считается.
- [x] Вынести тексты, описывающие тулзы, в отдельные модули, и импортировать их как из CLI, так и из GUI (обновлённый meta-issue #15).
- [x] Ещё касательно #15: в инитах основных модулей принимать проигнорированную исследователем опцию не только в виде `None`, но и в виде `''`.
- [x] Избавиться от интерактивного диалога пересоздания БД в пользу соответствующего элемента интерфейса (#25).

Проблемы:
- [ ] Невозможно на этапе получения сигнала от виджета проверить, ввёл ли исследователь путь к папке / имя БД (апстрим-фичреквест: https://github.com/streamlit/streamlit/issues/4645).
- [x] Для запуска веб-интерфейса придётся всё равно иметь дело с командной строкой (`streamlit run GUI.py`). Я-то потерплю, а каково будет небиоинформатикам? Возможное решение - создать .desktop-ярлык, но это не так уж и просто: #26.
